// derived from https://manual.gromacs.org/current/reference-manual/file-formats.html#gro

// NOTE: GROMACS stores all lengths (coordinates and box vectors) in nm.
// Internally matsci-parse uses Å.

// Its common convention for GROMACs to use Hw or Ow for water, we dont try to fix this at-all
// therefore cross format parsing (to a software that needs elemental indication) will probably fail.

import { createLattice } from "../lattice";
import { cartesian } from "../site";
import { fractional } from "../site/fractional";
import { Site } from "../site/site";
import { Structure } from "../structure/structure";
import { LengthUnitSystem } from "../units/length";

function pad5(str: string) {
  return str.length > 5 ? str.slice(0, 5) : str.padStart(5);
}

function formatCoord(x: number) {
  return x.toFixed(3).padStart(8);
}

export function fromGRO(text: string): Structure {
  const lines = text.split(/\r?\n/).filter((l) => l.length > 0);

  let cursor = 0;

  const title = lines[cursor++];

  const timeMatch = title.match(/t=\s*([-+]?[0-9]*\.?[0-9]+)/i);
  const time = timeMatch ? Number(timeMatch[1]) : undefined;

  const nAtoms = Number(lines[cursor++]);

  if (!Number.isFinite(nAtoms)) {
    throw new Error("Invalid GRO atom count");
  }

  type Atom = {
    symbol: string;
    cart: Float64Array;
  };

  const atoms: Atom[] = [];

  for (let i = 0; i < nAtoms; i++) {
    const line = lines[cursor++];

    const x = Number(line.slice(20, 28));
    const y = Number(line.slice(28, 36));
    const z = Number(line.slice(36, 44));

    let atomName = line.slice(10, 15).trim();

    let symbol = atomName.replace(/[0-9]/g, "");
    symbol = symbol.charAt(0).toUpperCase() + symbol.slice(1).toLowerCase();

    atoms.push({
      symbol,
      cart: new Float64Array(
        LengthUnitSystem.convertArray([x, y, z], "nm", "angstrom"),
      ),
    });
  }

  let lattice = null;

  const boxLine = lines[cursor];

  if (boxLine) {
    const vals = boxLine.trim().split(/\s+/).map(Number);

    const matrix = LengthUnitSystem.convertArray(
      [
        vals[0] ?? 0,
        vals[3] ?? 0,
        vals[4] ?? 0,
        vals[5] ?? 0,
        vals[1] ?? 0,
        vals[6] ?? 0,
        vals[7] ?? 0,
        vals[8] ?? 0,
        vals[2] ?? 0,
      ],
      "nm",
      "angstrom",
    );

    const hasOffDiagonal =
      matrix[1] !== 0 ||
      matrix[2] !== 0 ||
      matrix[3] !== 0 ||
      matrix[5] !== 0 ||
      matrix[6] !== 0 ||
      matrix[7] !== 0;

    lattice = hasOffDiagonal
      ? createLattice(matrix)
      : createLattice([matrix[0], matrix[4], matrix[8]]);
  }

  const sites: Site[] = atoms.map((atom) => ({
    species: { symbol: atom.symbol },
    frac: lattice
      ? fractional(lattice, atom.cart)
      : new Float64Array([NaN, NaN, NaN]),
  }));

  return {
    lattice,
    sites,
    time,
  };
}

export function toGRO(
  structure: Structure,
  options?: {
    title?: string;
    time?: number;
  },
): string {
  const title =
    options?.title ??
    (options?.time !== undefined
      ? `Generated structure, t=${options.time}`
      : "Generated by matsci-parse");

  const lines: string[] = [];

  lines.push(title);
  lines.push(String(structure.sites.length));

  for (let i = 0; i < structure.sites.length; i++) {
    const site = structure.sites[i];

    const cart = cartesian(structure.lattice, site);

    const [x, y, z] = LengthUnitSystem.convertArray(
      Array.from(cart),
      "angstrom",
      "nm",
    );

    lines.push(
      pad5("1") +
        pad5("RES") +
        pad5(site.species.symbol) +
        pad5(String(i + 1)) +
        formatCoord(x) +
        formatCoord(y) +
        formatCoord(z),
    );
  }

  const m = structure.lattice.basis.data;

  const [a, b, c] = LengthUnitSystem.convertArray(
    [m[0], m[4], m[8]],
    "angstrom",
    "nm",
  );

  lines.push([a, b, c].map((v) => v.toFixed(5)).join(" "));

  return lines.join("\n");
}
