import { fromParameters } from "../lattice";
import { createLattice } from "../lattice";
import { cartesian } from "../site";
import { fractional } from "../site/fractional";
import { Site } from "../site/site";
import { Structure } from "../structure/structure";

const DEFAULT_PADDING = 10.0;

function parseCRYST1(line: string) {
  const a = Number(line.slice(6, 15));
  const b = Number(line.slice(15, 24));
  const c = Number(line.slice(24, 33));

  const alpha = Number(line.slice(33, 40));
  const beta = Number(line.slice(40, 47));
  const gamma = Number(line.slice(47, 54));

  return { a, b, c, alpha, beta, gamma };
}

function isCRYST1Sane(
  a: number,
  b: number,
  c: number,
  extentX: number,
  extentY: number,
  extentZ: number,
): boolean {
  // reject degenerate or identity cells
  if (a <= 1e-3 || b <= 1e-3 || c <= 1e-3) return false;

  // reject clearly too small cells
  const margin = 1.2; // allow small packing inefficiency

  if (a < extentX * margin) return false;
  if (b < extentY * margin) return false;
  if (c < extentZ * margin) return false;

  // also reject ridiculous huge identity placeholders
  if (a === 1 && b === 1 && c === 1) return false;

  return true;
}

/** Parses a PDB (Protein Data Bank) string into a Structure. */
export function fromPDB(text: string): Structure {
  const lines = text.split(/\r?\n/);

  let crystal: {
    a: number;
    b: number;
    c: number;
    alpha: number;
    beta: number;
    gamma: number;
  } | null = null;

  type ParsedAtom = {
    symbol: string;
    x: number;
    y: number;
    z: number;
  };

  const atoms: ParsedAtom[] = [];

  let xmin = Infinity;
  let ymin = Infinity;
  let zmin = Infinity;

  let xmax = -Infinity;
  let ymax = -Infinity;
  let zmax = -Infinity;

  for (const line of lines) {
    if (line.startsWith("CRYST1")) {
      crystal = parseCRYST1(line);
      continue;
    }

    if (!line.startsWith("ATOM  ") && !line.startsWith("HETATM")) {
      continue;
    }

    const x = Number(line.slice(30, 38));
    const y = Number(line.slice(38, 46));
    const z = Number(line.slice(46, 54));

    let symbol = line.slice(76, 78).trim();

    if (!symbol) {
      symbol = line.slice(12, 16).replace(/[0-9]/g, "").trim();
      symbol = symbol.charAt(0).toUpperCase() + symbol.slice(1).toLowerCase();
    }

    atoms.push({ symbol, x, y, z });

    xmin = Math.min(xmin, x);
    ymin = Math.min(ymin, y);
    zmin = Math.min(zmin, z);

    xmax = Math.max(xmax, x);
    ymax = Math.max(ymax, y);
    zmax = Math.max(zmax, z);
  }

  if (atoms.length === 0) {
    throw new Error("No ATOM/HETATM records found.");
  }

  const extentX = xmax - xmin;
  const extentY = ymax - ymin;
  const extentZ = zmax - zmin;

  let lattice = createLattice([1, 0, 0, 0, 1, 0, 0, 0, 1]);

  let originX = xmin - DEFAULT_PADDING;
  let originY = ymin - DEFAULT_PADDING;
  let originZ = zmin - DEFAULT_PADDING;

  const useCrystal =
    crystal !== null &&
    isCRYST1Sane(crystal.a, crystal.b, crystal.c, extentX, extentY, extentZ);

  if (useCrystal) {
    lattice = fromParameters(
      crystal.a,
      crystal.b,
      crystal.c,
      crystal.alpha,
      crystal.beta,
      crystal.gamma,
    );

    originX = 0;
    originY = 0;
    originZ = 0;
  } else {
    const a = Math.max(extentX + 2 * DEFAULT_PADDING, 1.0);
    const b = Math.max(extentY + 2 * DEFAULT_PADDING, 1.0);
    const c = Math.max(extentZ + 2 * DEFAULT_PADDING, 1.0);

    lattice = createLattice([a, 0, 0, 0, b, 0, 0, 0, c]);
  }

  const sites: Site[] = atoms.map(({ symbol, x, y, z }) => ({
    species: { symbol },
    frac: fractional(
      lattice,
      new Float64Array([x - originX, y - originY, z - originZ]),
    ),
  }));

  return {
    lattice,
    sites,
  };
}

/** Serializes a Structure to a PDB string. */
export function toPDB(
  structure: Structure,
  options?: {
    title?: string;
  },
): string {
  const title = options?.title ?? "Generated by matsci-parse";

  const lines: string[] = [];

  lines.push(`HEADER    ${title}`);

  let index = 1;

  for (const site of structure.sites) {
    const c = cartesian(structure.lattice, site);

    const symbol = site.species.symbol;

    lines.push(
      [
        "ATOM  ",
        index.toString().padStart(5),
        " ",
        symbol.padEnd(4),
        " MOL ",
        "A",
        "   1    ",
        c[0].toFixed(3).padStart(8),
        c[1].toFixed(3).padStart(8),
        c[2].toFixed(3).padStart(8),
        "  1.00",
        "  0.00",
        "          ",
        symbol.padStart(2),
      ].join(""),
    );

    index++;
  }

  lines.push("END");

  return lines.join("\n");
}
