import { createLattice } from "../lattice/lattice";
import { Site } from "../site/site";
import { Structure } from "../structure/structure";
import { cartesian, fractional } from "../site";
import { LineReader } from "./helpers";

function isSelective(line: string): boolean {
  return line.toLowerCase().startsWith("selective");
}

function isCartesian(line: string): boolean {
  const l = line.trim().toLowerCase();
  return l.startsWith("c") || l.startsWith("k");
}

/** Parses a POSCAR/CONTCAR string into a Structure. */
export function fromPOSCAR(text: string): Structure {
  const r = new LineReader(text);

  // comment/title
  r.next();

  // scale factor
  const scale = Number(r.nextTrimmed());

  // lattice vectors (row-major)
  const latticeData: number[] = [];

  for (let i = 0; i < 3; i++) {
    const v = r.nextTrimmed().split(/\s+/).map(Number);

    if (v.length !== 3) {
      throw new Error("Invalid POSCAR lattice");
    }

    latticeData.push(v[0] * scale, v[1] * scale, v[2] * scale);
  }

  const lattice = createLattice(latticeData);

  // VASP5 species names
  const symbols = r.nextTrimmed().split(/\s+/);

  // atom counts
  const counts = r.nextTrimmed().split(/\s+/).map(Number);

  if (symbols.length !== counts.length) {
    throw new Error("Species/count mismatch");
  }

  // optional selective dynamics
  let selective = false;

  let line = r.nextTrimmed();
  if (isSelective(line)) {
    selective = true;
    line = r.nextTrimmed();
  }

  // direct is true unless cartesian is.
  let direct = true;
  direct = !isCartesian(line);

  const sites: Site[] = [];

  let speciesIndex = 0;
  let remaining = counts[0];

  const totalAtoms = counts.reduce((a, b) => a + b, 0);

  for (let i = 0; i < totalAtoms; i++) {
    const tokens = r.nextTrimmed().split(/\s+/);

    const coords = tokens.slice(0, 3).map(Number);

    const frac = direct
      ? new Float64Array(coords)
      : fractional(lattice, new Float64Array(coords));

    const props: Record<string, unknown> = {};

    if (selective) {
      const sd = tokens.slice(3, 6).map((t) => t.toLowerCase() === "t");

      if (sd.length === 3) {
        props.selectiveDynamics = sd as [boolean, boolean, boolean];
      }
    }

    sites.push({
      species: {
        symbol: symbols[speciesIndex],
      },
      frac,
      ...(Object.keys(props).length > 0 ? { properties: props } : {}),
    });

    remaining--;

    if (remaining === 0 && speciesIndex < counts.length - 1) {
      speciesIndex++;
      remaining = counts[speciesIndex];
    }
  }

  return {
    lattice,
    sites,
    selectiveDynamics: selective || undefined,
    _cursorEnd: r.count,
  };
}

/** Serializes a Structure to a POSCAR string. */
export function toPOSCAR(
  structure: Structure,
  options?: {
    title?: string;
    scale?: number;
    direct?: boolean;
  },
): string {
  const title = options?.title ?? "Generated by matsci-parse";
  const scale = options?.scale ?? 1.0;
  const direct = options?.direct ?? true;

  const lines: string[] = [];

  lines.push(title);
  lines.push(String(scale));

  // lattice
  const m = structure.lattice.basis.data;

  lines.push(`${m[0]} ${m[1]} ${m[2]}`);
  lines.push(`${m[3]} ${m[4]} ${m[5]}`);
  lines.push(`${m[6]} ${m[7]} ${m[8]}`);

  // preserve order of first appearance
  const grouped = new Map<string, typeof structure.sites>();

  for (const site of structure.sites) {
    const symbol = site.species.symbol;

    const group = grouped.get(symbol);

    if (group) {
      group.push(site);
    } else {
      grouped.set(symbol, [site]);
    }
  }


  const species = [...grouped.keys()];
  const sites = [...grouped.values()].flat();

  lines.push(species.join(" "));
  lines.push(species.map((s) => (grouped.get(s) ?? []).length).join(" "));

  const hasSelective = structure.selectiveDynamics ?? sites.some((s) => s.properties?.selectiveDynamics);

  if (hasSelective) {
    lines.push("Selective Dynamics");
  }

  lines.push(direct ? "Direct" : "Cartesian");

  for (const site of sites) {
    const coords = direct ? site.frac : cartesian(structure.lattice, site);

    let line = `${coords[0]} ${coords[1]} ${coords[2]}`;

    const sd = site.properties?.selectiveDynamics;

    if (sd) {
      line += ` ${sd.map((f: boolean) => (f ? "T" : "F")).join(" ")}`;
    }

    lines.push(line);
  }

  return lines.join("\n");
}
