import { createLattice } from "../lattice/lattice";
import { inverse } from "../lattice/inverse";
import { mul } from "../matrix/operations/mul";
import { createMatrix } from "../matrix/matrix";
import { Site } from "../site/site";
import { Structure } from "../structure/structure";
import { fractional } from "../site/fractional";

import { cartesian } from "../site";

function isSelective(line: string): boolean {
  return line.toLowerCase().startsWith("selective");
}

function isCartesian(line: string): boolean {
  const l = line.trim().toLowerCase();
  return l.startsWith("c") || l.startsWith("k");
}

// TODO: Currently nukes the selective dynamics flag from the input file.
// It would be good to restore this.
// TODO: would be good to ensure that the title is also optionally
// maintained.

export function fromPOSCAR(text: string): Structure {
  const lines = text.split("\n").map((x) => x.trim());

  let cursor = 0;

  // comment/title
  cursor++;

  // scale factor
  const scale = Number(lines[cursor++]);

  // lattice vectors (row-major)
  const latticeData: number[] = [];

  for (let i = 0; i < 3; i++) {
    const v = lines[cursor++].split(/\s+/).map(Number);

    if (v.length !== 3) {
      throw new Error("Invalid POSCAR lattice");
    }

    latticeData.push(v[0] * scale, v[1] * scale, v[2] * scale);
  }

  const lattice = createLattice(latticeData);

  // VASP5 species names
  const symbols = lines[cursor++].split(/\s+/);

  // atom counts
  const counts = lines[cursor++].split(/\s+/).map(Number);

  if (symbols.length !== counts.length) {
    throw new Error("Species/count mismatch");
  }

  // optional selective dynamics
  if (isSelective(lines[cursor])) {
    cursor++;
  }

  // direct is true unless cartesian is.
  let direct = true;
  direct = !isCartesian(lines[cursor]);

  cursor++;

  const sites: Site[] = [];

  let speciesIndex = 0;
  let remaining = counts[0];

  const latticeInv = !direct ? inverse(lattice) : null;

  const totalAtoms = counts.reduce((a, b) => a + b, 0);

  for (let i = 0; i < totalAtoms; i++) {
    const tokens = lines[cursor++].split(/\s+/);

    const coords = tokens.slice(0, 3).map(Number);

    const frac = direct
      ? new Float64Array(coords)
      : fractional(lattice, new Float64Array(coords));

    sites.push({
      species: {
        symbol: symbols[speciesIndex],
      },
      frac,
    });

    remaining--;

    if (remaining === 0 && speciesIndex < counts.length - 1) {
      speciesIndex++;
      remaining = counts[speciesIndex];
    }
  }

  return {
    lattice,
    sites,
    _cursorEnd: cursor,
  };
}

export function toPOSCAR(
  structure: Structure,
  options?: {
    title?: string;
    scale?: number;
    direct?: boolean;
  },
): string {
  const title = options?.title ?? "Generated by matsci-parse";
  const scale = options?.scale ?? 1.0;
  const direct = options?.direct ?? true;

  const lines: string[] = [];

  lines.push(title);
  lines.push(String(scale));

  // lattice
  const m = structure.lattice.basis.data;

  lines.push(`${m[0]} ${m[1]} ${m[2]}`);
  lines.push(`${m[3]} ${m[4]} ${m[5]}`);
  lines.push(`${m[6]} ${m[7]} ${m[8]}`);

  // preserve order of first appearance
  const grouped = new Map<string, typeof structure.sites>();

  for (const site of structure.sites) {
    const symbol = site.species.symbol;

    if (!grouped.has(symbol)) {
      grouped.set(symbol, []);
    }

    grouped.get(symbol)!.push(site);
  }

  const species = [...grouped.keys()];
  const sites = [...grouped.values()].flat();

  lines.push(species.join(" "));
  lines.push(species.map((s) => grouped.get(s)!.length).join(" "));

  lines.push(direct ? "Direct" : "Cartesian");

  for (const site of sites) {
    const coords = direct ? site.frac : cartesian(structure.lattice, site);

    lines.push(`${coords[0]} ${coords[1]} ${coords[2]}`);
  }

  return lines.join("\n");
}
