import { createLattice } from "../../lattice/lattice";
import { kspacingToGrid } from "../../lattice/kspacingToGrid";
import { ibravToLattice } from "./ibrav";
import { fractional } from "../../site";
import { getElement } from "../../data/periodictable/atomicData";
import type { Site } from "../../site/site";
import type { Structure } from "../../structure/structure";
import { parseQeNamelist, getNumber, getString, getArray } from "./namelist";
import type {
  AtomicSpeciesEntry,
  AtomicPositionEntry,
  CellParameterEntry,
  KPointsCard,
} from "./schema/cards";
import type { QeControlOptions } from "./schema/control";
import type { QeSystemOptions } from "./schema/system";
import type { QeElectronsOptions } from "./schema/electrons";

const BOHR_TO_ANGSTROM = 0.529177;

type AtomCoordMode = "crystal" | "angstrom" | "bohr" | "alat";

// ──────────────────────────────────────────────────────────────────────
//  Options — composed from schema types
// ──────────────────────────────────────────────────────────────────────

/** User-facing options for {@link toPW}. Composed from schema types. */
export interface QEOptions {
  control?: QeControlOptions;
  system?: QeSystemOptions;
  electrons?: QeElectronsOptions;
  kpoints?:
    | { grid: [number, number, number]; shift?: [number, number, number] }
    | { kspacing: number };
  pseudo?: { pseudos?: Record<string, string> };
}

const QE_DEFAULTS: Required<
  Pick<QEOptions, "control" | "system" | "electrons" | "kpoints" | "pseudo">
> = {
  control: {
    title: "Generated by matsci-parse",
    calculation: "scf",
    pseudo_dir: "./",
  },
  system: {
    ecutwfc: 30,
  },
  electrons: {
    conv_thr: 1e-6,
  },
  kpoints: { kspacing: 0.22 },
  pseudo: { pseudos: {} },
};

// ──────────────────────────────────────────────────────────────────────
//  fromPW — unchanged
// ──────────────────────────────────────────────────────────────────────

/** Parses a Quantum ESPRESSO PW input string into a Structure. */
export function fromPW(text: string): Structure {
  const namelists = parseQeNamelist(text);
  const lines = text.split("\n");

  // --- extract &SYSTEM parameters ---
  const ibrav = getNumber(namelists, "SYSTEM", "ibrav") ?? 0;
  const nat = getNumber(namelists, "SYSTEM", "nat");
  const celldm = getArray(namelists, "SYSTEM", "celldm", 6);

  // --- build lattice ---
  let lattice: ReturnType<typeof createLattice>;

  if (ibrav !== 0) {
    // ibravToLattice returns lattice vectors in Bohr → convert to angstrom
    const bohr = ibravToLattice(ibrav, celldm);
    const m = bohr.basis.data;
    lattice = createLattice([
      m[0] * BOHR_TO_ANGSTROM,
      m[1] * BOHR_TO_ANGSTROM,
      m[2] * BOHR_TO_ANGSTROM,
      m[3] * BOHR_TO_ANGSTROM,
      m[4] * BOHR_TO_ANGSTROM,
      m[5] * BOHR_TO_ANGSTROM,
      m[6] * BOHR_TO_ANGSTROM,
      m[7] * BOHR_TO_ANGSTROM,
      m[8] * BOHR_TO_ANGSTROM,
    ]);
  } else {
    // ibrav=0: lattice must come from CELL_PARAMETERS block
    const { lattice: cellLattice, units: cellUnits } =
      parseCellParameters(lines);

    if (cellUnits === "alat") {
      if (celldm[0] === 0) {
        throw new Error("CELL_PARAMETERS alat requires celldm(1) in &SYSTEM");
      }
      // lattice vectors are in units of celldm(1) Bohr → convert to angstrom
      const factor = celldm[0] / BOHR_TO_ANGSTROM;
      const m = cellLattice.basis.data;
      lattice = createLattice([
        m[0] * factor,
        m[1] * factor,
        m[2] * factor,
        m[3] * factor,
        m[4] * factor,
        m[5] * factor,
        m[6] * factor,
        m[7] * factor,
        m[8] * factor,
      ]);
    } else if (cellUnits === "bohr") {
      // lattice vectors in Bohr → convert to angstrom
      const m = cellLattice.basis.data;
      const factor = 1 / BOHR_TO_ANGSTROM;
      lattice = createLattice([
        m[0] * factor,
        m[1] * factor,
        m[2] * factor,
        m[3] * factor,
        m[4] * factor,
        m[5] * factor,
        m[6] * factor,
        m[7] * factor,
        m[8] * factor,
      ]);
    } else {
      // angstrom — use directly
      lattice = cellLattice;
    }
  }

  // --- parse atomic positions ---
  const {
    lines: atomLines,
    units,
    selectiveDynamics,
  } = parseAtomicPositions(lines);

  if (atomLines.length === 0) {
    throw new Error("ATOMIC_POSITIONS block not found");
  }

  if (nat !== undefined && atomLines.length !== nat) {
    throw new Error(
      `Expected ${nat} atoms (from &SYSTEM nat), got ${atomLines.length}`,
    );
  }

  const sites: Site[] = [];

  for (const line of atomLines) {
    const parts = line.split(/\s+/);
    const symbol = parts[0];
    const x = +parts[1];
    const y = +parts[2];
    const z = +parts[3];

    let frac: Float64Array;

    switch (units) {
      case "crystal":
        frac = new Float64Array([x, y, z]);
        break;

      case "angstrom":
        frac = fractional(lattice, new Float64Array([x, y, z]));
        break;

      case "bohr": {
        // Bohr → angstrom → fractional
        const angstrom = new Float64Array([
          x * BOHR_TO_ANGSTROM,
          y * BOHR_TO_ANGSTROM,
          z * BOHR_TO_ANGSTROM,
        ]);
        frac = fractional(lattice, angstrom);
        break;
      }

      case "alat": {
        // alat = celldm(1) Bohr → Bohr → angstrom → fractional
        if (celldm[0] === 0) {
          throw new Error(
            "ATOMIC_POSITIONS alat requires celldm(1) in &SYSTEM",
          );
        }
        const bohr = new Float64Array([
          x * celldm[0],
          y * celldm[0],
          z * celldm[0],
        ]);
        const angstrom = new Float64Array([
          bohr[0] / BOHR_TO_ANGSTROM,
          bohr[1] / BOHR_TO_ANGSTROM,
          bohr[2] / BOHR_TO_ANGSTROM,
        ]);
        frac = fractional(lattice, angstrom);
        break;
      }
    }

    const site: Site = { species: { symbol }, frac };

    if (selectiveDynamics && parts.length >= 7) {
      const ifPos = [+parts[4], +parts[5], +parts[6]];
      (site.properties ??= {}).ifPos = ifPos;
    }

    sites.push(site);
  }

  return {
    lattice,
    sites,
    ...(selectiveDynamics ? { selectiveDynamics: true } : {}),
  };
}

// ---------- internal parsing helpers ----------

interface CellParamsResult {
  lattice: ReturnType<typeof createLattice>;
  units: string;
}

function parseCellParameters(lines: string[]): CellParamsResult {
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (/^CELL_PARAMETERS/i.test(line)) {
      const unitMatch = line.match(
        /^CELL_PARAMETERS\s*(?:\{|\()?(\w+)(?:\}|\))?/i,
      );
      const units = unitMatch?.[1]?.toLowerCase() ?? "angstrom";

      const rows: number[][] = [];
      for (let j = 1; j <= 3; j++) {
        if (i + j >= lines.length) {
          throw new Error("Incomplete CELL_PARAMETERS block");
        }
        rows.push(lines[i + j].trim().split(/\s+/).map(Number));
      }

      return {
        lattice: createLattice([...rows[0], ...rows[1], ...rows[2]]),
        units,
      };
    }
  }

  throw new Error("CELL_PARAMETERS block not found");
}

interface AtomBlockResult {
  lines: string[];
  units: AtomCoordMode;
  selectiveDynamics: boolean;
}

function parseAtomicPositions(lines: string[]): AtomBlockResult {
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (/^ATOMIC_POSITIONS/i.test(line)) {
      const unitMatch = line.match(
        /^ATOMIC_POSITIONS\s*(?:\{|\()?(\w+)(?:\}|\))?/i,
      );
      const units = (unitMatch?.[1]?.toLowerCase() ??
        "angstrom") as AtomCoordMode;

      const atomLines: string[] = [];

      // check for "Selective dynamics" on the NEXT line
      let selectiveDynamics = false;
      let j = i + 1;
      if (j < lines.length && /^selective\s+dynamics/i.test(lines[j].trim())) {
        selectiveDynamics = true;
        j++;
      }

      for (; j < lines.length; j++) {
        const l = lines[j].trim();
        if (!l) break;

        const parts = l.split(/\s+/);
        if (
          parts.length < 4 ||
          !/^[A-Za-z]/.test(parts[0]) ||
          parts.slice(1, 4).some((x) => Number.isNaN(+x))
        ) {
          break;
        }

        atomLines.push(l);
      }

      return { lines: atomLines, units, selectiveDynamics };
    }
  }

  return { lines: [], units: "angstrom", selectiveDynamics: false };
}

// ──────────────────────────────────────────────────────────────────────
//  toPW — data-driven
// ──────────────────────────────────────────────────────────────────────

const RESERVED: Record<string, string[]> = {
  CONTROL: ["title"],
};

/** Serializes a Structure to a Quantum ESPRESSO PW input string. */
export function toPW(structure: Structure, options?: QEOptions): string {
  const ctrl = { ...QE_DEFAULTS.control, ...options?.control };
  const sys = { ...QE_DEFAULTS.system, ...options?.system };
  const { nat: _nat, ntyp: _ntyp, ibrav: _ibrav, ...sysOpts } = sys;
  const elec = { ...QE_DEFAULTS.electrons, ...options?.electrons };

  // --- derive card data from Structure ---
  const speciesOrder = collectSpecies(structure.sites);
  const species = buildAtomicSpecies(speciesOrder, options?.pseudo?.pseudos);
  const positions = buildAtomicPositions(structure);
  const cell = buildCellParameters(structure.lattice);
  const kpoints = buildKPoints(structure, options?.kpoints);

  // --- serialize ---
  const lines: string[] = [];

  lines.push(`title = '${ctrl.title}'`);
  lines.push("");
  writeNamelist(lines, "CONTROL", { ...ctrl, title: undefined });
  lines.push("");
  writeNamelist(lines, "SYSTEM", {
    ...sysOpts,
    nat: structure.sites.length,
    ntyp: speciesOrder.length,
    ibrav: 0,
  });
  lines.push("");
  writeNamelist(lines, "ELECTRONS", elec);
  lines.push("");

  lines.push(...serializeAtomicSpecies(species));
  lines.push("");
  lines.push(...serializeKPoints(kpoints));
  lines.push("");
  lines.push(...serializeCellParameters(cell));
  lines.push("");
  lines.push(
    ...serializeAtomicPositions(positions, structure.selectiveDynamics),
  );

  return lines.join("\n");
}

// ──────────────────────────────────────────────────────────────────────
//  Card builders — Structure + options → typed card data
// ──────────────────────────────────────────────────────────────────────

/** Collect unique species in first-appearance order. */
function collectSpecies(sites: Site[]): string[] {
  const seen = new Set<string>();
  const order: string[] = [];
  for (const site of sites) {
    const sym = site.species.symbol;
    if (!seen.has(sym)) {
      seen.add(sym);
      order.push(sym);
    }
  }
  return order;
}

/** Build ATOMIC_SPECIES rows from species order + pseudopotential map. */
function buildAtomicSpecies(
  speciesOrder: string[],
  pseudos?: Record<string, string>,
): AtomicSpeciesEntry[] {
  return speciesOrder.map((symbol) => {
    const el = getElement(symbol);
    return {
      symbol,
      mass: el?.mass ?? 0,
      pseudo: pseudos?.[symbol] ?? `${symbol}.UPF`,
    };
  });
}

/** Build ATOMIC_POSITIONS rows from Structure sites. */
function buildAtomicPositions(structure: Structure): AtomicPositionEntry[] {
  // group sites by species in first-appearance order
  const grouped = new Map<string, Site[]>();
  for (const site of structure.sites) {
    const sym = site.species.symbol;
    const group = grouped.get(sym);
    if (group) {
      group.push(site);
    } else {
      grouped.set(sym, [site]);
    }
  }

  const speciesOrder = collectSpecies(structure.sites);
  const entries: AtomicPositionEntry[] = [];

  for (const sym of speciesOrder) {
    const group = grouped.get(sym) ?? [];
    for (const site of group) {
      const entry: AtomicPositionEntry = {
        symbol: sym,
        x: site.frac[0],
        y: site.frac[1],
        z: site.frac[2],
      };
      if (site.properties?.ifPos) {
        entry.ifPos = [
          site.properties.ifPos[0],
          site.properties.ifPos[1],
          site.properties.ifPos[2],
        ];
      }
      entries.push(entry);
    }
  }

  return entries;
}

/** Build CELL_PARAMETERS rows from Lattice. */
function buildCellParameters(
  lattice: Structure["lattice"],
): CellParameterEntry[] {
  const m = lattice.basis.data;
  return [
    [m[0], m[1], m[2]],
    [m[3], m[4], m[5]],
    [m[6], m[7], m[8]],
  ];
}

/** Build K_POINTS card from options (with kspacing default). */
function buildKPoints(
  structure: Structure,
  kpoints?: QEOptions["kpoints"],
): KPointsCard {
  if (kpoints) {
    if ("grid" in kpoints) {
      return {
        mode: "automatic",
        grid: kpoints.grid,
        shift: kpoints.shift ?? [0, 0, 0],
      };
    }
    return {
      mode: "automatic",
      grid: kspacingToGrid(structure.lattice, kpoints.kspacing),
      shift: [0, 0, 0],
    };
  }
  return {
    mode: "automatic",
    grid: kspacingToGrid(structure.lattice, QE_DEFAULTS.kpoints.kspacing),
    shift: [0, 0, 0],
  };
}

// ──────────────────────────────────────────────────────────────────────
//  Card serializers — typed card data → string lines
// ──────────────────────────────────────────────────────────────────────

function serializeAtomicSpecies(entries: AtomicSpeciesEntry[]): string[] {
  const lines = ["ATOMIC_SPECIES"];
  for (const e of entries) {
    lines.push(`${e.symbol}  ${e.mass}  ${e.pseudo}`);
  }
  return lines;
}

function serializeKPoints(card: KPointsCard): string[] {
  switch (card.mode) {
    case "gamma":
      return ["K_POINTS gamma"];
    case "automatic":
      return [
        "K_POINTS automatic",
        `${card.grid[0]}  ${card.grid[1]}  ${card.grid[2]}  ${card.shift[0]}  ${card.shift[1]}  ${card.shift[2]}`,
      ];
    default:
      // list / bands / covering — not used by toPW but handled for completeness
      throw new Error(`K_POINTS mode '${card.mode}' not yet supported in toPW`);
  }
}

function serializeCellParameters(
  entries: CellParameterEntry[],
  unit: "angstrom" | "bohr" | "alat" = "angstrom",
): string[] {
  const lines = [`CELL_PARAMETERS ${unit}`];
  for (const [a, b, c] of entries) {
    lines.push(`${a} ${b} ${c}`);
  }
  return lines;
}

function serializeAtomicPositions(
  entries: AtomicPositionEntry[],
  selectiveDynamics?: boolean,
  unit: "crystal" | "angstrom" | "bohr" | "alat" = "crystal",
): string[] {
  const lines = [`ATOMIC_POSITIONS ${unit}`];
  if (selectiveDynamics) {
    lines.push("Selective dynamics");
  }
  for (const e of entries) {
    let suffix = "";
    if (e.ifPos) {
      suffix = ` ${e.ifPos[0]} ${e.ifPos[1]} ${e.ifPos[2]}`;
    }
    lines.push(`${e.symbol} ${e.x} ${e.y} ${e.z}${suffix}`);
  }
  return lines;
}

// ──────────────────────────────────────────────────────────────────────
//  Namelist serializer — generic key → value
// ──────────────────────────────────────────────────────────────────────

function writeNamelist(
  lines: string[],
  name: string,
  params: Record<string, unknown>,
): void {
  const reserved = new Set(RESERVED[name] ?? []);
  const entries = Object.entries(params).filter(
    ([k, v]) => !reserved.has(k) && v !== undefined,
  );
  if (entries.length === 0) {
    lines.push(`&${name}`);
    lines.push("/");
    return;
  }
  lines.push(`&${name}`);
  for (const [key, value] of entries) {
    if (typeof value === "string") {
      lines.push(`  ${key} = '${value}'`);
    } else if (typeof value === "boolean") {
      lines.push(`  ${key} = .${value ? "TRUE" : "FALSE"}.`);
    } else if (typeof value === "number" && !Number.isFinite(value)) {
      continue;
    } else {
      lines.push(`  ${key} = ${value}`);
    }
  }
  lines.push("/");
}
