// prettier-ignore
/** Space group data array indexed by space group number: [bravais_letter, centering, chiral]. */
export const spgroup_data = [
    null, // unused (SG = 0)
    ["a","P", false], ["a","P", true], ["m","P", false], ["m","P", false], 
    ["m","C", false], ["m","P", false], ["m","P", false], ["m","C", false], 
    ["m","C", false], ["m","P", true], ["m","P", true], ["m","C", true], 
    ["m","P", true], ["m","P", true], ["m","C", true], ["o","P", false], 
    ["o","P", false], ["o","P", false], ["o","P", false], ["o","C", false], 
    ["o","C", false], ["o","F", false], ["o","I", false], ["o","I", false], 
    ["o","P", false], ["o","P", false], ["o","P", false], ["o","P", false], 
    ["o","P", false], ["o","P", false], ["o","P", false], ["o","P", false],
    ["o","P", false], ["o","P", false], ["o","C", false], ["o","C", false],
    ["o","C", false], ["o","A", false], ["o","A", false], ["o","A", false],
    ["o","A", false], ["o","F", false], ["o","F", false], ["o","I", false],
    ["o","I", false], ["o","I", false], ["o","P", true], ["o","P", true], 
    ["o","P", true], ["o","P", true], ["o","P", true], ["o","P", true], 
    ["o","P", true], ["o","P", true], ["o","P", true], ["o","P", true],
    ["o","P", true], ["o","P", true], ["o","P", true], ["o","P", true],
    ["o","P", true], ["o","P", true], ["o","C", true], ["o","C", true],
    ["o","C", true], ["o","C", true], ["o","C", true], ["o","C", true],
    ["o","F", true], ["o","F", true], ["o","I", true], ["o","I", true],
    ["o","I", true], ["o","I", true], ["t","P", false], ["t","P", false],
    ["t","P", false], ["t","P", false], ["t","I", false], ["t","I", false],
    ["t","P", false], ["t","I", false], ["t","P", true], ["t","P", true],
    ["t","P", true], ["t","P", true], ["t","I", true], ["t","I", true], 
    ["t","P", false], ["t","P", false], ["t","P", false], ["t","P", false],
    ["t","P", false], ["t","P", false], ["t","P", false], ["t","P", false], 
    ["t","I", false], ["t","I", false], ["t","P", false], ["t","P", false], 
    ["t","P", false], ["t","P", false], ["t","P", false], ["t","P", false],
    ["t","P", false], ["t","P", false], ["t","I", false], ["t","I", false],
    ["t","I", false], ["t","I", false], ["t","P", false], ["t","P", false], 
    ["t","P", false], ["t","P", false], ["t","P", false], ["t","P", false], 
    ["t","P", false], ["t","P", false], ["t","I", false], ["t","I", false],
    ["t","I", false], ["t","I", false], ["t","P", true], ["t","P", true],
    ["t","P", true], ["t","P", true], ["t","P", true], ["t","P", true], 
    ["t","P", true], ["t","P", true], ["t","P", true], ["t","P", true], 
    ["t","P", true], ["t","P", true], ["t","P", true], ["t","P", true],
    ["t","P", true], ["t","P", true], ["t","I", true], ["t","I", true],
    ["t","I", true], ["t","I", true], ["h","P", false], ["h","P", false],
    ["h","P", false], ["h","R", false], ["h","P", true], ["h","R", true],
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","P", false],
    ["h","P", false], ["h","P", false], ["h","R", false], ["h","P", false], 
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","R", false], 
    ["h","R", false], ["h","P", true], ["h","P", true], ["h","P", true], 
    ["h","P", true], ["h","R", true], ["h","R", true], ["h","P", false],
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","P", false], 
    ["h","P", false], ["h","P", false], ["h","P", true], ["h","P", true], 
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","P", false], 
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","P", false], 
    ["h","P", false], ["h","P", false], ["h","P", false], ["h","P", false], 
    ["h","P", false], ["h","P", false], ["h","P", true], ["h","P", true],
    ["h","P", true], ["h","P", true], ["c","P", false], ["c","F", false],
    ["c","I", false], ["c","P", false], ["c","I", false], ["c","P", true],
    ["c","P", true], ["c","F", true], ["c","F", true], ["c","I", true], 
    ["c","P", true], ["c","I", true], ["c","P", false], ["c","P", false], 
    ["c","F", false], ["c","F", false], ["c","I", false], ["c","P", false],
    ["c","P", false], ["c","I", false], ["c","P", false], ["c","F", false],
    ["c","I", false], ["c","P", false], ["c","F", false], ["c","I", false],
    ["c","P", true], ["c","P", true], ["c","P", true], ["c","P", true],
    ["c","F", true], ["c","F", true], ["c","F", true], ["c","F", true], 
    ["c","I", true], ["c","I", true]];

// prettier-ignore
/** Centering symbols for each space group (1-indexed). */
export const centering = [
    "P","P","P","P","C","P","P","C","C","P","P","C","P","P","C","P","P","P",
    "P","C","C","F","I","I","P","P","P","P","P","P","P","P","P","P","C","C",
    "C","A","A","A","A","F","F","I","I","I","P","P","P","P","P","P","P","P",
    "P","P","P","P","P","P","P","P","C","C","C","C","C","C","F","F","I","I",
    "I","I","P","P","P","P","I","I","P","I","P","P","P","P","I","I","P","P",
    "P","P","P","P","P","P","I","I","P","P","P","P","P","P","P","P","I","I",
    "I","I","P","P","P","P","P","P","P","P","I","I","I","I","P","P","P","P",
    "P","P","P","P","P","P","P","P","P","P","P","P","I","I","I","I","P","P",
    "P","R","P","R","P","P","P","P","P","P","R","P","P","P","P","R","R","P",
    "P","P","P","R","R","P","P","P","P","P","P","P","P","P","P","P","P","P",
    "P","P","P","P","P","P","P","P","P","P","P","P","P","P","P","F","I","P",
    "I","P","P","F","F","I","P","I","P","P","F","F","I","P","P","I","P","F",
    "I","P","F","I","P","P","P","P","F","F","F","F","I","I"];
