import { VolumetricData } from "../volumetric";
import type { CartesianCoords, GridShape } from "../common";
import { CrystalStructure } from "../crystal";
import { Site } from "../common";
import { PeriodicTable } from "../../AtomicData";

import { stringToLines } from "../utils";

const BOHR_TO_ANGSTROM = 0.529177;
const ANGSTROM_TO_BOHR = 1.8897268;

/*
cube file documentation:
https://paulbourke.net/dataformats/cube/
*/
export function volumetricToCube(
  structure: CrystalStructure,
  volumetricData: VolumetricData,
): string {
  const lines: string[] = [];

  // Comment lines
  lines.push("Generated by matsci-parse");
  lines.push("Volumetric data export");

  // Origin in Å
  const origin = [...volumetricData.origin];
  const bohrOrigin = origin.map((x) => x * ANGSTROM_TO_BOHR);
  lines.push(
    `${structure.numSites} ${bohrOrigin.map((x) => x.toFixed(6)).join(" ")}`,
  );

  // Grid vectors
  const shape = volumetricData.shape;
  const basis = volumetricData.basis;

  for (let i = 0; i < 3; i++) {
    const vector = basis[i];
    const vectorBohr = basis[i].map((x) => x * ANGSTROM_TO_BOHR);
    lines.push(`${shape[i]} ${vectorBohr.map((x) => x.toFixed(6)).join(" ")}`);
  }

  // Atoms (sites)
  for (const site of structure.sites) {
    const symbol = structure.species[site.speciesIndex];

    // Find atomic number
    const atomicNumber = Object.values(PeriodicTable).find(
      (el) => el.symbol === symbol,
    )?.atomicNumber;

    if (!atomicNumber) {
      throw new Error(`Unknown element symbol: ${symbol}`);
    }

    const pos = [...site.cart];
    const posBohr = site.cart.map((x) => x * ANGSTROM_TO_BOHR);
    const charge = (site.getProp<number>("charge") ?? 0).toFixed(6);

    lines.push(
      `${atomicNumber} ${charge} ${posBohr.map((x) => x.toFixed(6)).join(" ")}`,
    );
  }

  // Volumetric data
  const values = volumetricData.values;
  const [nX, nY, nZ] = shape;

  let lineBuffer: string[] = [];
  for (let iz = 0; iz < nZ; iz++) {
    for (let iy = 0; iy < nY; iy++) {
      for (let ix = 0; ix < nX; ix++) {
        const idx = volumetricData.index(ix, iy, iz);
        lineBuffer.push(values[idx].toExponential(8));

        if (lineBuffer.length === 6) {
          lines.push(lineBuffer.join(" "));
          lineBuffer = [];
        }
      }
    }
  }
  // flush
  if (lineBuffer.length > 0) {
    lines.push(lineBuffer.join(" "));
  }

  return lines.join("\n");
}

function parseCube(lines: string[]): {
  structure: CrystalStructure;
  volumetricData: VolumetricData;
  linesConsumed: number;
} {
  let i = 0;

  // 1. Skip first two non-empty comment lines
  i += 2;

  const atomsOriginLine = lines[i].split(/\s+/);
  const nAtoms = parseInt(atomsOriginLine[0]);
  const originX = parseFloat(atomsOriginLine[1]);
  const originY = parseFloat(atomsOriginLine[2]);
  const originZ = parseFloat(atomsOriginLine[3]);

  let origin: CartesianCoords = [originX, originY, originZ];

  i++;

  const voxelOne = lines[i].split(/\s+/);
  const isBohr = parseInt(voxelOne[0], 10) > 0;

  let latVectors: CartesianCoords[] = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
  ];

  latVectors[0][0] = parseFloat(voxelOne[1]);
  latVectors[0][1] = parseFloat(voxelOne[2]);
  latVectors[0][2] = parseFloat(voxelOne[3]);

  i++;

  const voxelTwo = lines[i].split(/\s+/);
  latVectors[1][1] = parseFloat(voxelTwo[2]);
  latVectors[1][0] = parseFloat(voxelTwo[1]);
  latVectors[1][2] = parseFloat(voxelTwo[3]);

  i++;

  const voxelThree = lines[i].split(/\s+/);

  latVectors[2][0] = parseFloat(voxelThree[1]);
  latVectors[2][1] = parseFloat(voxelThree[2]);
  latVectors[2][2] = parseFloat(voxelThree[3]);

  const shape: GridShape = [0, 0, 0];

  shape[0] = parseInt(voxelOne[0], 10);
  shape[1] = parseInt(voxelTwo[0], 10);
  shape[2] = parseInt(voxelThree[0], 10);

  i++;

  // 4. Atom parsing
  const species: string[] = [];
  const speciesIndexMap = new Map<string, number>();
  const sites: Site[] = [];

  for (let a = 0; a < nAtoms; a++, i++) {
    const parts = lines[i].trim().split(/\s+/);
    if (parts.length < 5) throw new Error(`Malformed atom line: "${lines[i]}"`);

    const atomicNumber = parseInt(parts[0], 10);
    const charge = parseFloat(parts[1]);
    let position: CartesianCoords = [
      parseFloat(parts[2]),
      parseFloat(parts[3]),
      parseFloat(parts[4]),
    ];

    const element = PeriodicTable[atomicNumber];
    if (!element) throw new Error(`Unknown atomic number: ${atomicNumber}`);
    const symbol = element.symbol;

    let speciesIndex = speciesIndexMap.get(symbol);
    if (speciesIndex === undefined) {
      speciesIndex = species.length;
      species.push(symbol);
      speciesIndexMap.set(symbol, speciesIndex);
    }

    sites.push(new Site(speciesIndex, position, { charge }));
  }

  // if bohr we convert here
  if (isBohr) {
    sites.forEach((site) => {
      site.cart = site.cart.map((x) => x * BOHR_TO_ANGSTROM) as CartesianCoords;
    });
  }

  if (isBohr) {
    for (let j = 0; j < 3; j++) {
      for (let k = 0; k < 3; k++) {
        latVectors[j][k] *= BOHR_TO_ANGSTROM;
      }
    }
  }

  if (isBohr) {
    origin = origin.map((x) => x * BOHR_TO_ANGSTROM) as CartesianCoords;
  }

  const lattice: CartesianCoords[] = latVectors.map(
    (vec, i) => vec.map((v) => v * shape[i]) as CartesianCoords,
  );

  const structure = new CrystalStructure({
    lattice,
    species,
    sites,
  });

  // 5. Volumetric values
  const nValues = shape[0] * shape[1] * shape[2];
  const values = new Float32Array(nValues);
  let count = 0;

  while (i < lines.length && count < nValues) {
    const parts = lines[i++].trim().split(/\s+/);
    for (const p of parts) {
      if (!p) continue;
      if (count < nValues) {
        values[count] = parseFloat(p);
        count++;
      }
    }
  }

  if (count !== nValues) {
    throw new Error(`Cube file truncated: expected ${nValues}, got ${count}`);
  }

  // 6. Build VolumetricData
  const volumetricData = new VolumetricData({
    origin,
    basis: latVectors as [CartesianCoords, CartesianCoords, CartesianCoords],
    shape,
    values,
    units: "e/Å³",
  });

  return { structure, volumetricData, linesConsumed: i };
}

export function cubeToVolumetric(cubeString: string): VolumetricData {
  const lines = stringToLines(cubeString);
  return parseCube(lines).volumetricData;
}

export function cubeToStructure(cubeString: string): CrystalStructure {
  const lines = stringToLines(cubeString);
  return parseCube(lines).structure;
}
