import { describe, it, expect } from "vitest";
import { minkowski } from "@/core/matrix/operations/reduction/minkowski";
import { createMatrix } from "@/core/matrix/matrix";
import { mul } from "@/core/matrix/operations/mul";
import { determinant } from "@/core/matrix/operations/determinant";

function approx(a: number, b: number, eps = 1e-6) {
  expect(Math.abs(a - b)).toBeLessThan(eps);
}

/** Build an n×n Matrix from a flat row-major array. */
function mat(flat: number[], n: number) {
  return createMatrix(n, n, new Float64Array(flat));
}

/** Euclidean norm of row `i`. */
function norm(m: { data: Float64Array; cols: number }, i: number): number {
  let s = 0;
  for (let j = 0; j < m.cols; j++) s += m.data[i * m.cols + j] ** 2;
  return Math.sqrt(s);
}

/** det of a 2×2 flat (row-major) array. */
function det2(d: ArrayLike<number>): number {
  return d[0] * d[3] - d[1] * d[2];
}

/** Check a 2×2 basis is in the standard Minkowski (Gauss) reduced form:
 *   |a| ≤ |b|, and |a·b| ≤ |a|²/2 (with equality only when |a|=|b|). */
function isGaussReduced(m: { data: Float64Array; cols: number }): boolean {
  const d = m.data;
  const a = [d[0], d[1]];
  const b = [d[2], d[3]];
  const la = Math.hypot(a[0], a[1]);
  const lb = Math.hypot(b[0], b[1]);
  const dot = a[0] * b[0] + a[1] * b[1];
  if (la > lb + 1e-9) return false; // b must not be shorter than a
  if (lb < la - 1e-9) return true; // strictly longer second vector -> done
  return Math.abs(dot) <= la * la / 2 + 1e-9;
}

describe("minkowski", () => {
  it("throws on non-square matrix", () => {
    const m = createMatrix(2, 3, new Float64Array([1, 0, 0, 0, 1, 0]));
    expect(() => minkowski(m)).toThrow("square");
  });

  it("throws on singular (non full-rank) matrix", () => {
    const m = mat([1, 2, 2, 4], 2);
    expect(() => minkowski(m)).toThrow("full-rank");
  });

  it("reduces Z³ (identity input) to a valid integer basis", () => {
    const m = mat([1, 0, 0, 0, 1, 0, 0, 0, 1], 3);
    const { basis, transform } = minkowski(m);
    // Minkowski reduction of Z³ is a signed permutation of the standard basis:
    // every entry is 0 or ±1, the determinant is ±1, and all rows are unit vectors.
    for (let i = 0; i < 9; i++) {
      approx(Math.abs(basis.data[i]), basis.data[i] === 0 ? 0 : 1);
    }
    approx(Math.abs(determinant(basis)), 1);
    approx(Math.abs(determinant(transform)), 1);
    for (let i = 0; i < 3; i++) approx(norm(basis, i), 1);
  });

  it("reduces a 2D basis to Gauss-reduced form", () => {
    const m = mat([10, 1, 5, 3], 2);
    const { basis } = minkowski(m);
    expect(isGaussReduced(basis)).toBe(true);
  });

  it("finds the true shortest vector of a 2D lattice", () => {
    // Standard example: the reduced basis is (1,0),(1,1)-style with norm 1.
    const m = mat([6, 2, 7, 3], 2);
    const { basis } = minkowski(m);
    const norms = [norm(basis, 0), norm(basis, 1)].sort((a, b) => a - b);
    // The lattice generated by (6,2),(7,3) has shortest vector (1,1): norm √2.
    approx(norms[0], Math.SQRT2);
  });

  it("transform is unimodular (det = ±1)", () => {
    const m = mat([6, 2, 7, 3], 2);
    const { transform } = minkowski(m);
    expect(Math.abs(Math.abs(det2(transform.data)) - 1)).toBeLessThan(1e-6);
  });

  it("reduced = transform × original", () => {
    const m = mat([4, 1, 0, 3, 2, 1, 1, 0, 2], 3);
    const { basis, transform } = minkowski(m);
    const product = mul(transform, m);
    for (let i = 0; i < 9; i++) approx(product.data[i], basis.data[i]);
  });

  it("preserves the determinant (lattice volume)", () => {
    const m = mat([4, 1, 0, 3, 2, 1, 1, 0, 2], 3);
    const { basis } = minkowski(m);
    approx(determinant(basis), determinant(m));
  });

  it("3D reduction produces a strictly shorter first vector", () => {
    const m = mat([8, 0, 0, 0, 7, 0, 3, 2, 6], 3);
    const { basis } = minkowski(m);
    const first = norm(basis, 0);
    // the (3,2,6)-type combination is shorter than the 8-long input row
    expect(first).toBeLessThan(norm(m, 0));
    // first vector is no longer than any other reduced vector
    for (let i = 1; i < 3; i++) expect(first).toBeLessThanOrEqual(norm(basis, i) + 1e-9);
  });

  it("handles a 1×1 matrix", () => {
    const m = mat([7], 1);
    const { basis, transform } = minkowski(m);
    approx(basis.data[0], 7);
    approx(transform.data[0], 1);
  });

  it("2D already-reduced orthogonal basis is unchanged", () => {
    const m = mat([1, 0, 0, 2], 2);
    const { basis } = minkowski(m);
    approx(norm(basis, 0), 1);
    approx(norm(basis, 1), 2);
    expect(isGaussReduced(basis)).toBe(true);
  });

  it("reduces an integer 3×3 lattice and returns integer basis", () => {
    const m = mat([
      5, 1, 0,
      3, 2, 1,
      0, 4, 3,
    ], 3);
    const { basis, transform } = minkowski(m);
    for (let i = 0; i < 9; i++) {
      approx(basis.data[i], Math.round(basis.data[i]), 1e-9);
      approx(transform.data[i], Math.round(transform.data[i]), 1e-9);
    }
    approx(determinant(transform), 1);
  });

  it("negative entries work", () => {
    const m = mat([-3, 2, 1, -4], 2);
    const { basis, transform } = minkowski(m);
    expect(isGaussReduced(basis)).toBe(true);
    const product = mul(transform, m);
    for (let i = 0; i < 4; i++) approx(product.data[i], basis.data[i]);
  });
});
